module.exports = [
    {
        id: "dc1801f1-a7d0-4c7c-af18-cfc98637777b",
        recipe_name: "Fresh Spring Rolls",
        cuisine: "Vietnamese",
        servings: "8",
        total_cook_time: "50",
        image_url: "http://localhost:8080/images/fresh-rolls.jpeg",
        ingredients_line: "2 oz rice vermicelli%208 sheets of rice paper%208 large cooked shrimp%202 leaves of lettuce (Chopped)%203 tbsp fresh mint leaves (Chopped)%203 tbsp fresh cilantro (Chopped)%201 1/3 tbsp fresh thai basil (Chopped)",
        ingredients_base: "vermicelli%20rice paper%20shrimp%20lettuce%20mint%20cilantro%20basil",
        instructions: "Fill in a large pot with slightly salted water and bring to rolling boil.%20Stir in vermicelli and return to a boil.%20Cook vermicelli uncovered, stirring occasionaly until the vermecilli is tender yet firm to the bite, roughly 3-5 minutes.%20Fill a large bowl with warm water.%20Dip one sheet or rice paper into hot water to soften.%20Lay rice paper flat, place 2 shrimp halves in a row across the center.%20Add some vermicelli, lettuce, mint, cilantro and basil, leaving about 2 inches uncovered on each side%20Folder uncovered sides inward, then tightly roll the rice paper, beginning at the end with lettuce.%20Repeat with remaining ingredients and enjoy!"
    },
    {
        id: "ae40fdee-4e1e-4a17-bc9e-dcc68dd636d1",
        recipe_name: "Lamb Curry",
        cuisine: "Indian",
        servings: "6",
        total_cook_time: "180",
        image_url: "http://localhost:8080/images/lamb-curry.jpeg",
        ingredients_line: "2 lbs boneless (3 lbs bone-in) lamb stew meat, lamb shank or lamb shoulder steak%202 onions (Chopped)%202-3 tbsp ghee (clarified butter), or 1 tbsp extra virgin olive oil%202-3 tbsp curry powder, (to taste)%202 tsp salt%201 tbsp black pepper%201 tbsp ground coriander%201 tbsp cumin%201 tsp fresh rosemary (Chopped)%201 tsp dried thyme%202 slices lemon (with rind)%202 peeled and chopped apples (preferrably tart green apples)%201/4 cup golden raisins%201 1/2 cup chicken stock%201 1/2 lbs small potatoes, (Quartered)%202 cups basmati rice",
        ingredients_base: "lamb%20onion%20ghee%20curry powder%20salt%20black pepper%20ground coriander%20cumin%20rosemary%20thyme%20lemon%20apple%20raisin%20chicken stock%20potato%20rice",
        instructions: "Heat the ghee or the butter-with-olive-oil in a large, thick-bottomed pot (with cover) or Dutch oven on medium-high.%20Working in batches if necessary, brown the meat well on all sides and remove it from pan.%20Lower heat to medium low and add the curry powder to the ghee or oil, cook gently for 1-2 minutes.%20Add onions and garlic and cook for 5 minutes%20Return lamb to the pan.%20Add the coriander, black pepper, cumin, rosemary, thyme, sliced lemon, apples, raisins, chicken stock and salt.%20Bring to a simmer, reduce the heat to low, and cover the pot.%20Cook for 2 hours, check after 2 hours to see if meat is falling off the bone.%20Add potatoes, cook for another 45 minutes or until tender.%20While potatoes are cooking, cook the rice%20Put 2 cups of basmati rice in a medium thick-bottomed pot. Add 3 cups of water (less or more depending on package instructions), a tablespoon of butter or ghee, and a teaspoon of salt. Bring to a boil, lower the heat to a low simmer, cover the pot and let cook for 15 minutes.%20Remove from heat, covered and steam for 10 minutes. Fluff rice with fork.%20Test curry to desired liking."
    },
    {
        id: "daf57cba-7882-4bca-8aa1-2b2b1720df99",
        recipe_name: "French Onion Soup",
        cuisine: "French",
        servings: "4-6",
        total_cook_time: "80",
        image_url: "http://localhost:8080/images/french-onion-soup.jpeg",
        ingredients_line: "6 large onions (about 3 lbs)%204 tbsp extra virgin olive oil%202 tbsp butter%201 tsp sugar%20salt%202 cloves garlic (Minced)%208 cups chicken stock%202 bay leaves%201 tbsp fresh thyme leaves%201/2 tsp black pepper%208 slices french bread or baguette%201 1/2 cups gruyere cheese%20grated parmesan cheese",
        ingredients_base: "onions%20olive oil%20butter%20sugar%20salt%20garlic%20chicken stock%20bay leaf%20thyme%20black pepper%20baguette%20gruyere cheese%20parmesan cheese",
        instructions: "Peel and thinly slice the onions from root to stem. There should be about 10 cups of sliced onions in total.%20In a 5 to 6 quart thick-bottomed pot, heat 3 tablespoons of olive oil on medium heat. Add the onions and toss to coat with the olive oil.%20Cook the onions, stirring often, until they have softened, about 15 to 20 minutes.%20Increase the heat to medium high. Add the remaining tablespoon of olive oil and the butter and cook, stirring often, until the onions start to brown, about 20 to 40 minutes. The amount of time will vary depending on your pot, stove, and onions.%20Sprinkle with sugar (to help with the caramelization) and 1 teaspoon of salt. Continue to cook until the onions are well browned, about 10 to 15 more minutes.%20Add the minced garlic and cook for a minute more.%20Add the stock, bay leaves, and thyme. Bring to a simmer, cover the pot and lower the heat to maintain a low simmer. Cook for about 30 minutes.%20Season to taste with more salt and add freshly ground black pepper. Discard the bay leaves.%20While the soup is simmering, line a sheet pan with parchment paper or foil and preheat the oven to 450°F with a rack in the upper third of the oven.%20Brush both sides of the French bread or baguette slices lightly with olive oil (you'll end up using about a tablespoon and a half of olive oil for this).%20Put in the oven and toast until lightly browned, about 5 to 7 minutes. Remove from oven.%20Turn the toasts over and sprinkle with the grated Gruyere cheese and Parmesan. Return to oven when it's close to serving time and bake until the cheese is bubbly and lightly browned."
    },
    {
        id: "b1286532-1b32-4164-9b2b-c4d2515b78ed",
        recipe_name: "Spring Rolls",
        cuisine: "Chinese",
        servings: "15-20",
        total_cook_time: "30",
        image_url: "http://localhost:8080/images/spring-rolls.jpeg",
        ingredients_line: "2 tbsp oil%202 garlic cloves%20400g pork (Minced)%206 shitake mushrooms%201 1/2 cup carrots (Shredded)%201 1/2 cup bean sprouts%201 1/2 cup green cabbage (Shredded)%203 tsp cornstarch%201 1/2 tbsp oyster sauce%202 tsp soy sauce%2015-20 spring roll wrappers",
        ingredients_base: "oil%20garlic%20pork%20shitake mushroom%20carrot%20bean sprout%20cabbage%20cornstarch%20oyster sauce%20soy sauce%20spring roll wrapper",
        instructions: "Heat oil in a skillet or wok over high heat. Add garlic, stir quickly, then add pork. Cook, breaking it up as you go, until it turns white.%20Add carrot, bean sprouts, cabbage and mushrooms. Cook for 3 minutes or until vegetables are wilted. Add cornflour, soy sauce and Oyster sauce, cook for 1 minute until the liquid is gone.%20Cool Filling (super speedy: spread on tray, refrigerate 5 minutes).%20Mix cornflour and water in a small bowl (for sealing the rolls).%20Carefully peel off one spring roll wrapper, keep the others covered under a damp tea towel.%20Place the wrapper with the smooth side down in a diamond position. Place a very heaped dessert spoon of filling on the bottom. Roll up halfway, fold sides in, then finish rolling. Use cornflour sludge to seal.%20Repeat for remainder of wrappers%20Pour enough oil in a wok or large saucepan so it is double the height of the spring rolls. Heat on medium high until hot stick a bamboo chopstick or wooden spoon handle in, if rapid bubbles appear, then it is hot enough.%20Carefully place spring rolls in the oil (about 4 - 5 at a time) and cook, turning occasionally, until deep golden (around 1 1/2 - 2 minutes). Transfer to paper towels to drain.%20Repeat with remainder of spring rolls, server while hot!"
    },
    {
        id: "d225b10b-5b5c-4d06-a86a-b2814339c73a",
        recipe_name: "Chicken Shwarma",
        cuisine: "Middle Eastern",
        servings: "4-5",
        total_cook_time: "20",
        image_url: "http://localhost:8080/images/chicken-shwarma.jpeg",
        ingredients_line: "1 large garlic clove%201 tbsp ground coriander%201 tbsp ground cumin%201 tbsp ground cardamon%201 tsp ground cayenne pepper%202 tsp smoked paprika%202 tsp salt%20black pepper%202 tbsp lemon juice%203 tbsp olive oil%204-5 flatbreads%20sliced lettuce%20tomato slices%20red onion",
        ingredients_base: "garlic%20coriander%20cumin%20cardamon%20cayenne pepper%20paprika%20salt%20black pepper%20lemon juice%20olive oil%20flatbread%20lettuce%20tomato%20onion",
        instructions: "Combine the marinade ingredients in a large ziplock bag. Add the chicken, seal, the massage from the outside with your hands to make sure each piece is coated. Marinate 24 hours (minimum 3 hours).%20Heat a large non-stick skillet with 1 tablespoon over medium high heat, or lightly brush a BBQ hotplate/grills with oil and heat to medium high.%20Place chicken in the skillet or on the grill and cook the first side for 4 to 5 minutes until nicely charred. Turn and cook the other side for 3 to 4 minutes (the 2nd side takes less time).%20Remove chicken from the grill and cover loosely with foil. Set aside to rest for 5 minutes.%20Slice chicken and pile onto platter alongside flatbreads.%20To make a wrap, get a piece of flatbread, top with a bit of lettuce and tomato and Chicken Shawarma. Roll up and enjoy!"
    },
    {
        id: "69077909-3b1d-49ac-be73-b122a1dd4bd6",
        recipe_name: "Jerk Chicken",
        cuisine: "Jamaican",
        servings: "10",
        total_cook_time: "50",
        image_url: "http://localhost:8080/images/jerk-chicken.jpeg",
        ingredients_line: "10 chicken legs%201/3 cup olive oil%202 tbsp brown sugar%201 tbsp thyme%202 tsp ground allspice%202 tsp smoked paprika%201/4 - 1/2 tsp cinnamon%201 tsp ground ginger%201 tsp ground cloves%201 tsp cayenne pepper%201 tsp garlic powder%201 tsp onion powder%202 1/4 tsp salt%201/4 tsp ground black pepper",
        ingredients_base: "chicken%20olive oil%20brown sugar%20thyme%20allspice%20paprika%20cinnamon%20ginger%20cloves%20cayenne pepper%20garlic powder%20onion powder%20salt%20black pepper",
        instructions: "Preheat oven to 425F with rack on lower middle position. Use paper towels to thoroughly dry chicken legs of excess moisture. Use fork to poke holes on all sides of chicken legs. Set aside.%20In a bowl, combine all remaining ingredients to form a spice rub/paste mixture. Evenly rub mixture underneath the skin of chicken legs (easiest to use clean hands to really push the mixture as far underneath skin as you can) as well as on top.%20Place chicken on large rimmed/foil-lined baking sheet, with space in between each piece. Bake about 40 minutes or until nicely browned. Serve immediately."
    },
    {
        id: "e4ab36ad-4208-47dc-8469-2b5277b637dd",
        recipe_name: "Steakhouse Burger",
        cuisine: "American",
        servings: "8",
        total_cook_time: "25",
        image_url: "http://localhost:8080/images/hamburger.jpeg",
        ingredients_line: "2 slices white bread%201/3 cup milk%202 1/2 tsp salt%201 tsp ground black pepper%203 garlic cloves (Minced)%201 1/2 tbsp worcestershire sauce%202 tbsp ketchup%203 lbs 80 - 85% lean ground beef%203 scallions%208 hamburger buns",
        ingredients_base: "bread%20milk%20salt%20black pepper%20garlic%20worcestershire sauce%20ketchup%20beef%20scallion%20hamburger bun",
        instructions: "Preheat the grill to high heat.%20In a large bowl, mash the bread and milk together with a fork until it forms a chunky paste. Add the salt, pepper, garlic, Worcestershire sauce and ketchup and mix well.%20Add the ground beef and scallions and break the meat up with your hands. Mix everything together until evenly combined.%20Divide the mixture into 8 equal portions and form compact balls. Flatten the balls into ¾-inch patties about 4½ inches across. Form a slight depression in the center of each patty to prevent the burgers from puffing up on the grill.%20Oil the grilling grates. Grill the burgers, covered, until nicely browned on the first side, 2 to 4 minutes. Flip burgers and continue cooking for a few minutes more until desired doneness is reached.%20Before serving, toast the buns on the cooler side of the grill if desired."
    },
    {
        id: "fb8dc71e-483d-4876-92a5-b32c1714b4b5",
        recipe_name: "Amatriciana",
        cuisine: "Italian",
        servings: "4-6",
        total_cook_time: "30",
        image_url: "http://localhost:8080/images/amatriciana.jpeg",
        ingredients_line: "1 28oz can whole peeled tomatoes%202 tbsp olive oil, more for serving%201/4 lb pancetta%203 cloves garlic (Chopped)%201 tsp red pepper flakes%206 basil leaves%20salt and pepper%201 lb spaghetti%201 tbsp parsley (Chopped)%20grated parmigiano-reggiano",
        ingredients_base: "tomato%20olive oil%20pancetta%20garlic%20red pepper flake%20basil%20salt%20pepper%20spaghetti%20parsley%20parmigiano reggiano",
        instructions: "Puree the tomatoes to a smooth, creamy consistency in a food processor or with an immersion blender; set aside.%20Heat the olive oil over medium-high heat in a large skillet. When hot, add the guanciale and saute 5 to 7 minutes, until golden brown.%20Add the garlic and red pepper flakes and saute 1 minute. Add the pureed tomatoes, basil, and salt and pepper to taste. Reduce the heat to medium low and stir well. Cook, uncovered, 15 minutes, or until the sauce darkens and thickens. Toss with just-cooked pasta and serve with a sprinkling of parsley and cheese and a drizzle of olive oil."
    },
    {
        id: "e210d05f-13dc-41a5-89b2-f6a24b2a39f1",
        recipe_name: "Fish Taco",
        cuisine: "Mexican",
        servings: "4",
        total_cook_time: "21",
        image_url: "http://localhost:8080/images/fish-taco.jpeg",
        ingredients_line: "1 lb cod%202-3 tsp chili powder%201 tsp salt%201/2 cup sour cream%201/4 cup mayonnaise%203-4 tbsp lime juice%204 cup cabbage%2012 flour tortillas%201 avocado (Sliced)%204 radishes (Thinly Sliced)%204 spring onions (Thinly Sliced)%201/3 cup cilantro (Roughly Chopped)",
        ingredients_base: "cod%20chili powder%20salt%20sour cream%20mayonnaise%20lime juice%20cabbage%20tortillas%20avocado%20radish%20spring onion%20cilantro",
        instructions: "In a small bowl, combine the sour cream, mayonnaise, lime juice, and hot sauce (if using) for the taco sauce. Stir until combined.%20In a medium bowl, combine the shredded cabbage with 3 tablespoons of the taco sauce. Stir to coat and add more taco sauce if you like.%20In a dry skillet over medium-high heat, warm the tortillas one at a time for about 30 seconds on both sides. Alternatively, wrap 1 to 3 tortillas in a damp paper towel and microwave for 30 seconds, until warm.%20Sprinkle the fish on both sides with chili powder and salt. Gently rub in the seasonings with your fingers to make sure the fish is entirely coated.%20Warm a large cast iron or nonstick skillet on the stovetop over medium-high heat. When hot, add one tablespoon of olive oil and tilt the pan to entirely coat the bottom.%20Add the fish to the pan and cook for 2 minutes. Flip the fish and cook another 2 minutes. Flip and cook 1-2 minutes longer if needed; the fish is done when it is opaque all the way through and breaks apart easily.%20Transfer the cooked fillets to a platter and use a fork or a knife to gently break the fish into large chunks. Assemble the tacos with a few pieces of fish, some cabbage slaw, toppings of your choice, and a drizzle of taco sauce."
    },
    {
        id: "2f505954-95f7-481c-9a00-add3530bcead",
        recipe_name: "Chicken Fettuccine Alfredo",
        cuisine: "Italian",
        servings: "4",
        total_cook_time: "25",
        image_url: "http://localhost:8080/images/chicken-alfredo.jpeg",
        ingredients_line: "salt and ground black pepper%2012oz fettuccine%20olive oil%202 chicken breasts%208 tbsp unsalted butter%202 cups heavy cream%202 pinches grated nutmeg%201 1/2 cup parmigiano-reggiano",
        ingredients_base: "salt%20black pepper%20olive oil%20chicken%20butter%20heavy cream%20nutmeg%20parmigiano reggiano",
        instructions: "Bring a large pot of water to a boil, and salt generously. Add the pasta and cook according to package directions until al dente.%20Meanwhile, slice the chicken into 1/4-inch-thick strips, and lay them on a plate or a sheet of waxed paper. Season with salt and pepper.%20Heat a large skillet over medium heat. Add 2 tablespoons of the butter. When the butter melts, raise the heat to medium-high and add the chicken in 1 layer.%20Cook, without moving the pieces, until the underside has browned, 1 to 2 minutes. Flip the pieces, and cook until browned and cooked through, 2 to 3 minutes more. Transfer the chicken to a medium bowl.%20Reduce the heat to medium. Add the remaining 6 tablespoons butter. Scrape the bottom of the skillet with a wooden spoon to release any browned bits.%20When the butter has mostly melted, whisk in the cream and nutmeg and bring to a simmer, then cook for 2 minutes. Lower the heat to keep the sauce just warm.%20Whisk the Parmigiano-Reggiano into the sauce. Add the chicken and cooked pasta and toss well. Season with salt and pepper. Serve hot in heated bowls."
    },
    {
        id: "b91b0b09-b5a8-4a8a-a045-029025a13999",
        recipe_name: "Chicken Salad",
        cuisine: "American",
        servings: "4",
        total_cook_time: "30",
        image_url: "http://localhost:8080/images/chicken-salad.jpeg",
        ingredients_line: "1 lb chicken breast%202 stalk celery (Chopped)%201/2 red bell pepper (Chopped)%204-6 green olives (Pitted and Minced)%201/4 red onion (Chopped)%201/2 - 1 apple (Chopped)%201/3 head lettuce (Sliced and Chopped)%205 tbsp mayonnaise%201 tbsp plum preserve%202 tsp lemon juice%20salt and pepper",
        ingredients_base: "chicken%20celery%20bell pepper%20olive%20onion%20apple%20lettuce%20mayonnaise%20plum preserve%20lemon juice%20salt%20pepper",
        instructions: "Bring a pot with 2 quarts of well salted water (1 tablespoon salt) to a boil. Add the chicken breast (cut into large chunks) and return the water to a simmer. Then turn off the heat, and cover the pot. Let the chicken sit for 15 minutes (time it) or more while you prepare everything else.%20Prepare the chicken salad dressing in a large bowl. Mix together the mayonnaise, preserves, and lemon juice. Taste for the proper balance of sweetness and acidity. The salad dressing should not be too sweet, nor too sour.%20Mix in the chopped celery, bell pepper, olives, red onion, and apple.%20Remove the chicken from the poaching water and dice it. (Or dice already cooked chicken if that is what you are using for this salad.) Mix it in with the dressing and vegetables.%20When ready to serve, fold in the sliced and chopped iceberg lettuce."
    },
    {
        id: "46c89a61-35c3-4d0f-9e67-ffcfbde8ce95",
        recipe_name: "Pan-Seared Steak",
        cuisine: "American",
        servings: "4",
        total_cook_time: "20",
        image_url: "http://localhost:8080/images/steak.jpeg",
        ingredients_line: "2 new york strip steaks (or steak of your choosing)%201/2 tbsp vegetable oil%201 1/2 tsp salt%201 tsp black pepper%202 tbsp unsalted butter%202 cloves garlic (Quartered)%201 sprig rosemary",
        ingredients_base: "steak%20oil%20salt%20black pepper%20butter%20garlic%20rosemary",
        instructions: "Thoroughly pat steak dry with paper towels. Just before cooking, generously season with 1 1/2 tsp salt and 1 tsp black pepper.%20Heat the cast iron pan until hot then add 1/2 Tbsp oil over medium-high heat, swirling to coat.%20Once the oil is very hot, add steaks to the skillet. Sear the steaks on the first side for 4 minutes until a brown crust has formed then flip and cook another 3-4 minutes. Using tongs, turn the steak on its sides to render the white fat and sear the edges (1-minute per edge).%20Reduce heat to medium and immediately add 2 Tbsp butter, quartered garlic cloves and rosemary to the pan. Spoon the butter sauce over the steak, tilting the pan to get butter on your spoon.%20Continue spooning the sauce over the steak for a minute or until the steak is about 5-10 degrees from your desired doneness (the temperature will continue to rise another 5-10 degrees while steaks rest).%20Transfer steak to a cutting board, loosely cover and rest 10 minutes before slicing. Spoon extra butter sauce over sliced steak to serve."
    },
    {
        id: "7a81f33c-3101-4038-8f88-a134ed4d6dd4",
        recipe_name: "Pierogi",
        cuisine: "European",
        servings: "12",
        total_cook_time: "120",
        image_url: "http://localhost:8080/images/pierogi.jpeg",
        ingredients_line: "2 lb potatoes%202 tsp salt%204 tbsp butter (Melted)%202oz cream cheese%203/4 cup mozzarella cheese%201 cup warm water%201/4 cup whole milk%202 tbsp sour cream%203 tbsp olive oil%201 large egg%204 cup all purpose flour%204oz bacon (Chopped)",
        ingredients_base: "potato%20salt%20butter%20cream cheese%20mozzarella%20milk%20sour cream%20olive oil%20egg%20flour%20bacon",
        instructions: "Place potatoes in a pot, add enough water to cover potatoes then bring to a boil over medium/high and continue cooking 25 minutes or until easily pierced with a fork. Drain and cool 5 minutes then mash potatoes.%20Mash in 1/2 tsp salt, 2 Tbsp melted butter and 2 oz cream cheese. Mash in 3/4 cup shredded mozzarella cheese. Partially cover and set aside while rolling out the dough.%20In the bowl of a stand mixer (or large mixing bowl if mixing by hand), whisk together 1 cup warm water, 1/4 cup milk, 2 Tbsp sour cream, 1 egg, 3 Tbsp oil, and 1 1/2 tsp salt until blended.%20Using the dough hook attachment, add 2 cups flour and mix on speed 2 until incorporated. Add remaining flour 1/2 cup at a time, letting it incorporate before adding more. Add the last bit of flour 1 Tbsp at a time just until dough no longer sticks to sides of the bowl. Knead on speed 2 or by hand for 2-3 minutes until dough is smooth and elastic. Cover with plastic wrap and let rest for 30 minutes.%20Divide dough into 2 pieces. Cover the second piece and thinly roll the first piece out onto a floured surface to just under 1/8” thickness.%20Use a 3” diameter round cookie cutter to cut circles from the dough, keeping them as close as possible (collect scraps and place under the bowl to re-use). Add 1/2 Tbsp of potatoes over each round.%20To form pierogi, pull the 2 edges together and pinch tightly to seal. To ensure a tight seal, crimp the edges a second time with a pinch and twist motion. Cook or freeze pierogi for a future dinner.%20Make the topping before boiling pierogi so it’s ready to drizzle over pierogi to prevent sticking. In a medium skillet, saute 4 oz chopped bacon. Once crisp, melt in 2 Tbsp butter and remove from heat.%20Bring a pot of water to a rolling boil and add 1 Tbsp salt. Add fresh or frozen pierogi. Once they are floating and water is back to a boil and pierogi are floating, remove to a bowl with a slotted spoon drizzling buttery bacon between layers."
    },
    {
        id: "f49a5149-3c49-439a-b52a-30df3bc45949",
        recipe_name: "Tom Yum Soup",
        cuisine: "Thai",
        servings: "4-6",
        total_cook_time: "30",
        image_url: "http://localhost:8080/images/tom-yum.jpeg",
        ingredients_line: "6 cup chicken stock%201 stalk lemongrass (Minced)%201 carrot (Sliced)%204 cloves garlic (Minced)%203 tbsp onion (Minced)%202 tbsp galangal or ginger%203 bay leaves%201 1/2 tbsp fish sauce%201/2 tbsp soy sauce%201 tsp lime juice%201-2 cups shiitake mushrooms%201 small zucchini (Sliced)%2012-14 medium shrimps%201 cup cherry tomatoes (Sliced)%2013.5oz coconut milk%201 tsp chili oil%20brown sugar to taste%20crushed chili pepper flakes%201/3 cup cilantro",
        ingredients_base: "chicken stock%20lemongrass%20carrot%20garlic%20onion%20ginger%20bay leaf%20fish sauce%20soy sauce%20lime juice%20shiitake mushroom%20zucchini%20shrimp%20tomato%20coconut milk%20chili oil%20sugar%20chili pepper flakes%20cilantro",
        instructions: "Pour the stock into a deep cooking pot over medium-high heat. Add the prepared lemongrass, including the upper sections of the stalk you didn't mince. Boil 5 to 6 minutes to soften.%20Add carrot, garlic, onion, galangal or ginger, lime leaves, 1 1/2 tablespoons of the fish sauce, soy sauce, and lime juice. Reduce heat slightly, cover, and continue simmering 5 minutes. Add the mushrooms and zucchini, and continue simmering another 5 minutes.%20Add shrimp and cherry tomatoes. Cook 3 minutes or until shrimp are pink and plump.%20Turn down the heat to low and add 1/4 can coconut milk, chile oil, and brown sugar and red pepper flakes to taste (if using). Add the remaining teaspoon of fish sauce or more chile oil to taste. Discard the lime or bay leaves and the zest, if using. Serve with fresh cilantro sprinkled over and enjoy."
    },
    {
        id: "41a74e97-2f55-4c5f-929c-54ab452565f2",
        recipe_name: "Beef Tacos",
        cuisine: "Mexican",
        servings: "4",
        total_cook_time: "20",
        image_url: "http://localhost:8080/images/beef-taco.jpeg",
        ingredients_line: "1 lb 85% lean ground beef%201 tsp ground cumin%201 tsp smoked paprika%201/2 tsp garlic powder%201/2 tsp chili powder%201/2 tsp salt%201/2 tsp black pepper%201 pint cherry tomatoes (Quartered)%201/2 sweet onion (Diced)%201/2 cup cilantro (Chopped)%201/2 lime (Juiced)%204 flour tortillas%20cheese of your choice%201 avocado (Diced)",
        ingredients_base: "beef%20cumin%20paprika%20garlic powder%20chili powder%20salt%20black pepper%20tomato%20onion%20cilantro%20lime juice%20tortilla%20cheese%20avocado",
        instructions: "Heat a skillet over medium heat. With ground beef, I rarely add any oil to the skillet because it tends to be fattier.%20Once the skillet it hot, add the ground beef and break it apart with a wooden spoon.%20Cook, stirring and breaking apart the beef often, until it begins to brown. Add in the cumin, paprika, garlic powder, chili powder, salt and pepper. Stir well to disperse all the seasonings. Cook until the beef is just browned.%20Serve the ground beef in tacos (warm corn or flour tortillas in the oven for a few minutes), on nachos or in salads. We like to top ours with a quick pico de gallo, fresh cilantro, white cheddar cheese, diced avocado and pickled onions.%20Quick Pico: Toss the tomatoes, onion, cilantro and lime juice together in a bowl. Season with a pinch of salt and pepper",
    },
    {
        id: "bcdbd7e3-aedc-4067-bff1-12741a9e50f4",
        recipe_name: "Sushi Roll",
        cuisine: "Japanese",
        servings: "8",
        total_cook_time: "65",
        image_url: "http://localhost:8080/images/sushi.jpeg",
        ingredients_line: "1 1/3 cups water%202/3 sushi rice%203 tbsp rice vinegar%203 tbsp white sugar%201 1/2 tsp salt%204 sheets nori%201/2 lb imitation crabmeat (Flaked)%201 avocado (Sliced)%201/2 cucumber (Cut into strips)%202 tbsp pickled ginger",
        ingredients_base: "rice%20rice vinegar%20sugar%20seaweed%20imitation crab%20avocado%20cucumber%20pickled ginger",
        instructions: "Preheat the oven to 300 degrees F (150 degrees C).%20Bring water to a boil in a medium pot; stir in rice. Reduce heat to medium-low, cover, and simmer until rice is tender and water has been absorbed, 20 to 25 minutes.%20Mix rice vinegar, sugar, and salt in a small bowl. Gently stir into cooked rice in the pot and set aside.%20Lay nori sheets on a baking sheet.%20Heat nori in the preheated oven until warm, 1 to 2 minutes.%20Center 1 nori sheet on a bamboo sushi mat. Use wet hands to spread a thin layer of rice on top. Arrange 1/4 of the crabmeat, avocado, cucumber, and pickled ginger over rice in a line down the center. Lift one end of the mat and roll it tightly over filling to make a complete roll. Repeat with remaining ingredients.%20Use a wet, sharp knife to cut each roll into 4 to 6 slices."
    },
    {
        id: "96bbe262-cb6c-4ecc-ad3d-07396d40948c",
        recipe_name: "Lobster Bisque",
        cuisine: "French",
        servings: "4",
        total_cook_time: "55",
        image_url: "http://localhost:8080/images/lobster-bisque.jpeg",
        ingredients_line: "4 lobster tails%204 tbsp butter%201 tbsp olive oil%201 onion (Finely Chopped)%202 carrots (Chopped)%202 stalks celery (Chopped)%201 tsp thyme%201 tsp tarragon%201 tsp chicken bouillon powder%201/2 tsp salt%201/4 tsp black pepper%206 cloves garlic (Minced)%202 tbsp tomato paste%203 tbsp all purpose flour%201 1/4 cup white wine%204 cups lobster stock or seafood stock%203/4 - 1 cup heavy cream",
        ingredients_base: "lobster%20butter%20olive oil%20onion%20carrot%20celery%20thyme%20tarragon%20chicken bouillon%20salt%20black pepper%20garlic%20tomato paste%20flour%20white wine%20seafood stock%20heavy cream",
        instructions: "Fill a large pot with 5 cups of water. Stir in 1 teaspoon sea salt and bring to a boil.%20Add the lobster tails, cover with lid and let boil for 5 minutes, or until bright red.%20Remove lobster tails, reserving the liquid stock. When the lobsters have cooled slightly, remove the meat from the shells, reserving the meat and any liquid that comes out of the shells.%20Return lobster shells back to the water in the pot. Bring to a boil, reduce heat to medium-low and let simmer for a further 15 minutes to draw as much flavour out of the shells as possible.%20While stock is simmering, chop the meat into bite-sized pieces and refrigerate.%20Heat butter and oil in a large, heavy-based pot over medium heat, Sweat the onions, carrots, celery and fresh herbs. Cook until soft, about 5 minutes. Season with the bouillon powder, salt and pepper/s. Stir in 4 cloves of minced garlic and cook until fragrant, about 1 minute.%20Mix in tomato paste, cook for a further minute to coat vegetables. Sprinkle over flour and cook, while stirring occasionally for a further 2 minutes.%20Pour in wine, simmer and let reduce to half. Stir in lobster stock, reduce heat and gently simmer while stirring occasionally, until liquid has thickened slightly and flavours have blended, about 30 minutes.%20Take off the heat, transfer mixture to a blender and blend until smooth. Alternatively, purée with an immersion blender until very smooth. Return to medium-low heat and stir in heavy cream."
    },
    {
        id: "3b0f7276-1843-46e6-8ca6-6dc411c6b84e",
        recipe_name: "Pulled Pork",
        cuisine: "American",
        servings: "16",
        total_cook_time: "620",
        image_url: "http://localhost:8080/images/pulled-pork.jpeg",
        ingredients_line: "1/4 cup brown sugar%201 tbsp chili%201 tbsp paprika%202 tsp garlic powder%202 tsp salt%201 tsp black pepper%201 tsp cayenne pepper%201 pork shoulder roast%204 onions (Halved)%201 bottle bbq sauce",
        ingredients_base: "sugar%20chili%20paprika%20garlic powder%20salt%20black pepper%20cayenne pepper%20pork%20onion%20bbq sauce",
        instructions: "Stir together the brown sugar, chili, paprika, garlic powder, salt, black pepper and cayenne in a small bowl. Rub the mixture all over the pork shoulder. Wrap the pork in plastic wrap and refrigerate for several hours or preferably overnight.%20Preheat the oven to 300 degrees F.%20Place the pork in a large pot on a bed of the onion halves. Roast until fork-tender and falling apart, about 7 hours. Remove the pork from the pot and set it on a cutting board. Slice some of the onion.%20Place the pot on the stove over medium-high heat and add 1/2 to 1 cup of hot water. Scrape the pan to loosen up the bits and cook for 5 minutes to reduce. Pour in the barbecue sauce and stir to heat.%20Shred the meat with two forks, add the sliced onions to the pork and then toss in the barbecue sauce until it's coated to your liking! Serve plain or on hamburger rolls."
    },
    {
        id: "c58db8dd-a065-4ab2-9e40-6aac7a96f48c",
        recipe_name: "Butter Chicken",
        cuisine: "Indian",
        servings: "6",
        total_cook_time: "35",
        image_url: "http://localhost:8080/images/butter-chicken.jpeg",
        ingredients_line: "2.2 lbs chicken breast%202 tbsp lemon juice%204 clove garlic (Minced)%203 tbsp garam masala%203 tsp salt%201/4 cup vegetable oil%202 1/2 cups onion (Chopped)%202 tsp paprika%201/4 tsp cinnamon%202 cups tomatoes (Diced)%203/4 cup heavy cream%202 tbsp butter%201 tbsp cilantro",
        ingredients_base: "chicken%20lemon juice%20garlic%20garam masala%20salt%20oil%20onion%20paprika%20cinnamon%20tomato%20heavy cream%20butter%20cilantro",
        instructions: "Combine all ingredients in a zip-top bag or shallow baking dish, massaging the marinade into the chicken. Let stand at room temperature while you prepare the sauce, or marinate in the fridge overnight.%20Heat oil over medium heat in a large saucepan or dutch oven. Add onions and slowly cook until golden, about 20 minutes, reducing heat if they are getting crispy or browning quickly.%20Add garlic and cook until fragrant, about 1 minute. Stir in garam masala, paprika, cinnamon and salt; cook 1 minute more. Add tomatoes; cook 2 minutes, then add cream and carefully puree using an immersion blender (or standing blender, but do it in batches or the steam will blow the top off).%20Return sauce to saucepan and bring to a simmer. Remove chicken from marinade and it to the sauce (discarding remaining marinade). Cover, and simmer over medium-low heat until cooked through, about 12 minutes (remove a couple of pieces to make sure they are no longer pink inside). A gentle simmer is required to gently cook the breasts so they don’t become tough, and you don’t want to overcook them.%20Stir in butter, taste and add more salt to taste. Serve sprinkled with cilantro, if desired."
    },
    {
        id: "38a11c2d-43f1-4ad8-a459-d60bcefb4ea4",
        recipe_name: "Chicken Tika Skewers",
        cuisine: "Indian",
        servings: "6",
        total_cook_time: "140",
        image_url: "http://localhost:8080/images/chicken-tika-skewer.jpeg",
        ingredients_line: "3 chicken breasts%20120g greek yogurt%202 cloves garlic (Minced)%201 tbsp ginger (Minced)%201/2 lemon (Juiced)%201 tsp ground coriander%201/2 tsp turmeric%201/2 tsp cumin%201 tsp paprika%201/2 tsp mild chili powder%201 pinch cinnamon%201/2 tsp salt%201/2 tsp black pepper%202 tbsp vegetable oil%202 tbsp coriander (Chopped)",
        ingredients_base: "chicken%20yogurt%20garlic%20ginger%20lemon%20coriander%20turmeric%20cumin%20paprika%20chili powder%20cinnamon%20salt%20black pepper%20oil",
        instructions: "Place the chicken breast pieces into a bowl or freezer bag with the yogurt, garlic, ginger, lemon juice, coriander, turmeric, cumin, paprika, chilli powder, cinnamon, salt and pepper.%20Mix together so that everything is combined, then cover and place in the fridge to marinate for 2-3 hours.%20If you're using wooden skewers, place them in water to soak while the chicken is marinating. This will help to prevent them burning during grilling.%20Remove the marinated chicken from the fridge and thread onto skewers.%20Brush the chicken with the oil, then place on a griddle plate and cook, turning a couple of times, for 8-10 minutes until cooked through. Alternatively, you can grill (broil) under a grill, or you can barbecue for the same amount of time.%20Make sure the chicken is cooked by slicing into a larger piece and ensuring it's no longer pink in the middle.%20Serve with a sprinkling of freshly chopped coriander."
    },
    {
        id: "f32e521d-7982-4241-a4e7-c78934a03078",
        recipe_name: "Borscht Soup",
        cuisine: "Ukranian",
        servings: "10",
        total_cook_time: "70",
        image_url: "http://localhost:8080/images/borscht-soup.jpeg",
        ingredients_line: "3 medium beets (Grated)%204 tbsp olive oil%208 cups chicken broth%202 cups water%203 medium potatoes (Sliced)%202 carrots (Sliced)",
        ingredients_base: "beet%20oil%20chicken broth%20potato%20carrot",
        instructions: "Peel, grate and/or slice all vegetables (keeping sliced potatoes in cold water to prevent browning until ready to use then drain).%20Heat a large soup pot (5 1/2 Qt or larger) over medium/high heat and add 2 Tbsp olive oil. Add grated beets and sauté 10 minutes, stirring occasionally until beets are softened.%20Add 8 cups broth and 2 cups water. Add sliced potatoes and sliced carrots then cook for 10-15 minutes or until easily pierced with a fork.%20While potatoes are cooking, place a large skillet over medium/high heat and add 2 Tbsp oil. Add chopped onion, celery and bell pepper. Saute stirring occasionally until softened and lightly golden (7-8 minutes). Add 4 Tbsp Ketchup and stir fry 30 seconds then transfer to the soup pot to continue cooking with the potatoes.%20When potatoes and carrots reach desired softness, add 1 can of beans with their juice, 2 bay leaves, 2-3 Tbsp white vinegar, 1 tsp salt, 1/4 tsp black pepper, 1 pressed garlic clove, and 3 Tbsp chopped dill. Simmer for an additional 2-3 minutes and add more salt and vinegar to taste."
    },
    {
        id: "e24e00c8-cec0-44b9-9769-90faf1501da1",
        recipe_name: "Fried Rice",
        cuisine: "Asian",
        servings: "8",
        total_cook_time: "35",
        image_url: "http://localhost:8080/images/fried-rice.jpeg",
        ingredients_line: "3 cups cooked rice%202 tbsp sesame oil%201 small onion (Chopped)%201 cup frozen peas and carrots%202-3 tbsp soy sauce%202 eggs (Lightly Beaten)%202 tbsp green onions (Chopped)",
        ingredients_base: "rice%20sesame oil%20onion%20pea%20carrot%20soy sauce%20egg%20green onion",
        instructions: "Preheat a large skillet or wok to medium heat. Pour sesame oil in the bottom. Add white onion and peas and carrots and fry until tender.%20Slide the onion, peas and carrots to the side, and pour the beaten eggs onto the other side. Using a spatula, scramble the eggs. Once cooked, mix the eggs with the vegetable mix.%20Add the rice to the veggie and egg mixture. Pour the soy sauce on top. Stir and fry the rice and veggie mixture until heated through and combined. Add chopped green onions if desired."
    },
    {
        id: "ce846cd4-db09-42b7-984a-50a5f143431c",
        recipe_name: "Pad Kra Pao",
        cuisine: "Thai",
        servings: "1-2",
        total_cook_time: "20",
        image_url: "http://localhost:8080/images/pad-kra-pai.png",
        ingredients_line: "600g lean ground beef%202 tbsp oil%208 cloves garlic%202 shallots%202 chili pepper%201 tbsp regular soy sauce%201/2 tbsp dark soy sauce%201 tbsp oyster sauce%203/4 tbsp fish sauce%203/4 tbsp sugar%201 large handul thai basil%201 large egg",
        ingredients_base: "beef%20oil%20garlic%20shallot%20chili pepper%20soy sauce%20dark soy sauce%20oyster sauce%20fish sauce%20sugar%20basil%20egg",
        instructions: "Peel Thai basil leaves, rinse them, dry with paper towel, and set aside for later.%20Fine chop shallots, garlic, and chilies.%20Heat up a wok over high heat with oil then add the chopped shallots, garlic, and chilies. Stir for 30 seconds.%20Add lean ground beef. Continue to cook and break it apart until 80% cooked through. about 3-5 minutes.%20Add soy sauce, dark soy sauce, oyster sauce, fish sauce, and sugar. Mix to combine.%20Add your large handful of basil leaves, then stir for 1 minute. Serve on top of white rice and top with a crispy fried egg."
    },
    {
        id: "7113bb3a-fb6a-4356-9a6e-d17762291453",
        recipe_name: "Bun Bo Hue",
        cuisine: "Vietnamese",
        servings: "8",
        total_cook_time: "210",
        image_url: "http://localhost:8080/images/bun-bo-hue.jpeg",
        ingredients_line: "2 lb beef shank%202 lb oxtail%202 lb pork hock%201 lb pork sausage%201 lb pork blood%208 quartz water%2024oz chicken broth%2012 stalks lemongrass%202 large onions (halved)%203 tbsp salt%202 tbsp sugar%202 tbsp shrimp paste%203-4 tbsp fish sauce%203 tbsp anatto seeds%203 tbsp cooking oil%202 tbsp shallot (Sliced)%202 tbsp garlic (Minced)%20mint%20basil%20bean sprouts%20lime%2014oz dried rice noodle",
        ingredients_base: "beef%20ox tail%20pork hock%20pork blood%20sausage%20chicken broth%20lemongrass%20onion%20salt%20sugar%20shrimp paste%20fish sauce%20anatto seed%20oil%20shallot%20garlic%20mint%20basil%20bean sprout%20lime%20rice noodle",
        instructions: "Clean the meat: Add all meat to a stock pot and enough water to submerge it, bring to a boil. Drain and rinse thoroughly under running water.%20Add the meat, broth, lemongrass and onions to the pot and fill with water almost to the brim. Bring to a boil then drop the heat to medium-high to maintain a low boil. Add the seasoning.%20Let it simmer and periodically check the meats for doneness and remove them as they finish cooking. The pork should be done after about an hour, the beef can vary between 2-3 hours.%20After all the meat has removed, let it cool, then slice it. Adjust seasoning and add water to the broth pot if necessary.%20Make the aromatics & coloring then add it to the pot.%20Boil noodles according to package instructions.%20Assemble your bowl, and serve with herbs and veg on a side platter."
    },
    {
        id: "06a27b1b-4a74-474b-8b55-e5068c047483",
        recipe_name: "Tex-Mex Turkey Soup",
        cuisine: "American",
        servings: "6",
        total_cook_time: "50",
        image_url: "http://localhost:8080/images/tex-mex-soup.jpeg",
        ingredients_line: "1 tbsp olive oil%201/2 cup onion (Minced)%203 cloves garlic (Minced)%202 tsp chili powder%201/2 tsp cumin%201/2 tsp oregano%204 cups water%201 can condensed tomato soup%201 can diced tomatoes%201 cup salsa%204 cups shredded turkey%201 tbsp parsley%203 chicken bouillon cubes%201 can black beans%202 cups corn%201/2 cup sour cream%201/4 cup cilantro (Chopped)",
        ingredients_base: "oil%20onion%20garlic%20chili powder%20cumin%20oregano%20tomato soup%20tomato%20salsa%20turkey%20parsley%20chicken bouillon%20bean%20corn%20sour cream%20cilantro",
        instructions: "Heat olive oil in a large saucepan over medium heat. Add minced onions and cook until onions begin to soften, about 4 minutes. Add garlic, chili powder, cumin and oregano and cook, stirring, for 1 minute.%20Stir in water, tomato soup, diced tomatoes, salsa, shredded turkey, parsley and bouillon cubes. Bring to a boil, then reduce heat, and simmer 5 minutes or until bouillon cubes dissolve. Add black beans, corn, sour cream and cilantro. Simmer for 20 to 30 minutes.%20Serve with additonal toppings"
    },
    {
        id: "9833801a-639b-4775-b6f2-7b19cf4fbd15",
        recipe_name: "Wonton Soup",
        cuisine: "Chinese",
        servings: "50",
        total_cook_time: "25",
        image_url: "http://localhost:8080/images/wonton-soup.jpeg",
        ingredients_line: "50 wonton wrappers%20200g lean pork (Minced)%20200g shrimp%202 tbsp ginger%202 shallots%202 1/2 tbsp light soy sauce%203 1/2 tbsp chinese cooking wine%201/2 tsp salt%202 1/2 tbsp sesame oil%203 cup chicken broth%202 garlic cloves%202 tsp sugar",
        ingredients_base: "wonton wrapper%20pork%20shrimp%20ginger%20shallot%20light soy sauce%20cooking wine%20salt%20sesame oil%20chicken broth%20garlic%20sugar",
        instructions: "Place Filling ingredients in a bowl. Use a potato masher to mash until fairly smooth - about 20 mashes. Don't turn the prawn into a complete paste, small chunks are good.%20Lay Wontons on work surface. Use 2 teaspoons to put the Filling on the wontons. Work in batches of 5 if starting out, up to 15 or 20 if confident. Brush 2 edges with water. Fold to seal, pressing out air. Brush water on one corner and bring corners together, pressing to seal.%20Place wrapped wontons into a container with a lid as you work (so they don't dry out).%20To cook: bring a large pot of water to boil. Place wontons in water and cook for 4 minutes or until they float. Remove with slotted spoon straight into serving bowls. Ladle over broth.%20Place Broth ingredients in a saucepan over high heat. Add white ends of scallions/shallots if leftover from Wonton filling. %20Place lid on, bring to simmer then reduce to medium high and simmer for 5 - 10 minutes to allow the flavours to infuse. Pick garlic and ginger out before using.%20Ladle soup over wontons. Serve!"
    },
    {
        id: "142175c2-9b2e-4896-9be8-fd7f2feebfa3",
        recipe_name: "Lemongrass Chicken Vermicelli",
        cuisine: "Vietnamese",
        servings: "4",
        total_cook_time: "30",
        image_url: "http://localhost:8080/images/chicken-vermicelli.jpeg",
        ingredients_line: "600g chicken thigh fillets%201 stalk lemongrass%202 garlic cloves%202 tbsp lime juice%202 tbsp fish sauce%201 tbsp soy sauce%202 tbsp brown sugar%201 1/2 tbsp vegetable oil%20200g vermicelli noodles%202 carrots (Julienned)%202 cucumbers (Julienned)%205 cups lettuce (Sliced)%203 cups bean sprouts%20handful of mint leaves%20handful of cilantro%20sliced red chili%20lime wedges",
        ingredients_base: "chicken%20lemongrass%20garlic%20lime juice%20fish sauce%20brown sugar%20oil%20vermicelli noodle%20carrot%20cucumber%20lettuce%20bean sprout%20mint%20cilantro%20chili%20lime",
        instructions: "Combine Chicken and Marinade ingredients and set aside for at least 1 hour, up to 24 hours.%20Heat 1/2 tbsp oil in a fry pan over medium heat (or heat the BBQ). Remove chicken from marinade, shaking off large bits of lemongrass (small bits should fall off during cooking).%20Place chicken in the pan and cook each side until dark golden brown and chicken is just cooked through - about 6 to 8 minutes in total.%20Remove from pan, shaking off any remaining bits of visible lemongrass and set aside to rest for 5 minutes. Then slice into thin pieces.%20Soak the vermicelli noodles in hot water for 3 minutes (or according to packet instructions), then drain and rinse under cold water to stop the noodles from sticking together.%20Place noodles in bowl. Top with vegetables and herbs, and sliced chicken pieces. Drizzle with a few tablespoons of Nuoc Cham Sauce (be generous, ~ 4 tbsp per serving) and serve with lime wedges."
    },
    {
        id: "6375c338-dd16-4eb0-a35a-a8333bfd8568",
        recipe_name: "Rack of Lamb",
        cuisine: "French",
        servings: "2-3",
        total_cook_time: "130",
        image_url: "http://localhost:8080/images/lamb-rack.jpeg",
        ingredients_line: "1 lamb rack (Frenched)%202 tsp rosemary%201 tsp thyme%202 cloves garlic (Minced)%20salt%20black pepper%202 tsp olive oil",
        ingredients_base: "lamb%20rosemary%20thyme%20garlic%20salt%20black pepper%20oil",
        instructions:"Rub rib rack(s) all over with mixture of rosemary, thyme, and garlic. Rub with salt and freshly ground black pepper. Place in a thick plastic bag with olive oil.%20Remove the lamb from the refrigerator 1 1/2 to 2 hours before you cook it so that it comes to room temp. If the meat is not at room temperature, it won't cook evenly and may still be raw inside while the outside is cooked.%20Preheat the oven to 450°F, Arrange the oven rack, so the lamb will be in the middle of the oven.%20Rub the rack all over with more salt and pepper. Place the lamb rack bone side down (fat side up) on a roasting pan lined with foil. Wrap the exposed rib bones in a little foil so they don't burn.%20Place the roast in the oven at 450°F for 10 minutes (longer if roasting more than one rack), or until the surface of the roast is nicely browned.%20Then, lower the heat to 300°F. Cook for 10 to 20 minutes longer.%20Cut lamb chops away from the rack by slicing between the bones. Serve 2-3 chops per person."
    },
    {
        id: "a3b3a693-b87e-4c9b-809b-18d0129033e1",
        recipe_name: "Butternut Squash Soup",
        cuisine: "American",
        servings: "6",
        total_cook_time: "45",
        image_url: "http://localhost:8080/images/butternut-squash-soup.jpeg",
        ingredients_line: "2 tbsp olive oil%201 large onion (Chopped)%201/2 tsp salt%203 lbs butternut squash (Cubed)%203 garlic cloves (Chopped)%201 tbsp sage%201/2 tbsp rosemary%201 tsp ginger (Grated)%203-4 cups vegetable broth%20black pepper",
        ingredients_base: "oil%20onion%20salt%20squash%20garlic%20sage%20rosemary%20ginger%20vegetabe broth%20black pepper",
        instructions: "Heat the oil in a large pot over medium heat. Add the onion, salt, and several grinds of fresh pepper and sauté until soft, 5 to 8 minutes. Add the squash and cook until it begins to soften, stirring occasionally, for 8 to 10 minutes.%20Add the garlic, sage, rosemary, and ginger. Stir and cook 30 seconds to 1 minute, until fragrant, then add 3 cups of the broth. Bring to a boil, cover, and reduce heat to a simmer. Cook until the squash is tender, 20 to 30 minutes.%20Let cool slightly and pour the soup into a blender, working in batches if necessary, and blend until smooth. If your soup is too thick, add up to 1 cup more broth and blend. Season to taste and serve with parsley, pepitas, and crusty bread."
    },
    {
        id: "240bd4b0-f6de-43f2-b032-ae5f36df5f07",
        recipe_name: "Dan Dan Noodles",
        cuisine: "Asian",
        servings: "6",
        total_cook_time: "90",
        image_url: "http://localhost:8080/images/dandan-noodle.jpeg",
        ingredients_line: "2 1/2tbsp sichuan peppercorns%201 cinnamon stick%202 star anise%201 1/2 cup oil%201/4 cup crushed red pepper flakes%208oz ground pork%202 tsp hoisin sauce%202 tsp cooking wine%201 tsp dark soy sauce%201 tsp five spice powder%202 tbsp sesame paste%203 tbsp soy sauce%202 tsp sugar%202 clove garlic%201/2 cup chili oil%201 lb dried white noodle%201 small bunch leafy greens%20peanuts%20scallion",
        ingredients_base: "peppercorn%20cinnamon%20star anise%20oil%20red pepper flakes%20pork%20hoisin sauce%20cooking wine%20dark soy sauce%20five spice powder%20sesame paste%20soy sauce%20sugar%20chili oil%20noodle%20vegetable%20peanut%20scallion",
        instructions: "To make the meat mixture: In a wok, heat a teaspoon of oil over medium heat, and brown the ground pork. Add the sweet bean sauce, shaoxing wine, dark soy sauce, and five spice powder. Cook until all the liquid is evaporated. Set aside. Heat the other 2 teaspoons of oil in the wok over medium heat for a few minutes. Set aside.%20To make the sauce: Mix together all the sauce ingredients. Taste and adjust seasoning if you like. You can loosen it with more hot water, add more Sichuan peppercorn powder, etc.%20To prepare the noodles and veggies: Cook the noodles according to package directions and drain. Blanch the greens in the noodle water, and drain.%20Mix everything together and enjoy!"
    },
    {
        id: "31c5fdc8-f6ff-49d4-95d9-58196504c430",
        recipe_name: "Koobideh Kabob",
        cuisine: "Persian",
        servings: "8",
        total_cook_time: "35",
        image_url: "http://localhost:8080/images/koobideh.jpeg",
        ingredients_line: "1 lb lamb (Ground)%201 lb beef (Ground)%201 onion%202 tsp salt%201 tsp black pepper%201/2 tsp turmeric",
        ingredients_base: "lamb%20beef%20onion%20salt%20black pepper%20turmeric",
        instructions: "Combine the ground meat, grated onion, salt, pepper and turmeric in a mixing bowl. Knead the mixture for about 5 minutes into a cohesive pasty dough-like mass that can be molded and will not drop off easily.%20Divide the kabob mixture into 8 portions. Dampen your hands with the saved onion juice or plain water.%20Take a portion of the mixture and roll it into an oval sausage shape of 4 to 5 inches.%20Arrange the skewers spacing them apart, directly over the grill without the grate, about 3 to 4 inches above the glowing coals.%20Within a few seconds, start flipping the skewers over. This helps cook the meat on the outside and attach it to the skewer. It is important to flip them over before they cook too much on one side, or the meat on the other side will fall off.%20The kabobs should be grilled for a total time of 4 to 5 minutes on each side. The meat should have a nice brown sear outside and cooked well inside (not pink)."
    },
    {
        id: "5cd633bc-b95b-421c-9dc9-a92b287d0d6a",
        recipe_name: "Lobster Ravioli",
        cuisine: "Italian",
        servings: "6",
        total_cook_time: "60",
        image_url: "http://localhost:8080/images/lobster-ravioli.jpeg",
        ingredients_line: "1 lb pasta dough%2012oz lobster%201 cup ricotta%20lemon zest%20salt and pepper%206 tbsp butter%204 sage leaves%201 garlic clove (Chopped)",
        ingredients_base: "pasta dough%20lobster%20ricotta%20lemon%20salt%20pepper%20butter%20sage%20garlic",
        instructions: "Break lobster meat up into small pieces. Place in a bowl with ricotta, lemon zest, salt, and pepper. Mix well.%20Roll pasta dough out, using around ⅛th of the dough at a time. Keep your surface and hands well-floured so it doesn't stick. If using a pasta machine rather than your hands, roll to around the “5” setting. You want it very thin, almost see-through, but still holding together.%20Dab water between each pile of filling, along the edges where you want the ravioli to seal. Place another layer of ravioli dough over the top and seal in the filling. Try to avoid any air remaining in the filling pocket.%20Place the ravioli into the pot of boiling water a few at a time and cook for a couple of minutes. You will need to keep the heat relatively high to keep the water boiling. The ravioli will float up to the top when done.%20Melt butter in a skillet. When the butter begins bubbling slightly, add chopped garlic and stir in the butter for 1 minute.%20Add the chopped sage to the garlic butter, then continue stirring for an additional 1-2 minutes, until the butter turns light brown and has a rich, nutty aroma.%20Once they float to the top and are done cooking, remove ravioli from the water with a slotted spoon and place them into a serving dish. Drizzle over sage brown butter sauce. Repeat with the remainder of the ravioli.%20Serve, and enjoy!"
    },
    {
        id: "e42bf0b7-3577-4986-8f34-97e1beb4c8eb",
        recipe_name: "Chicken Souvlaki",
        cuisine: "Greek",
        servings: "8",
        total_cook_time: "40",
        image_url: "http://localhost:8080/images/chicken-souvlaki.jpeg",
        ingredients_line: "4 chicken breasts%206 tbsps olive oil%201 lemon (Juiced)%203 clove garlic (Minced)%202 tbsp oregano%20salt and pepper%201 cucumber%20500g yogurt%201-2 tbsps red wine vinegar%208 pita breads%201 tomato (Sliced)%201 onion (Sliced)%201/2 head lettuce (Chopped)",
        ingredients_base: "chicken%20oil%20lemon%20garlic%20oregano%20salt%20black pepper%20cucumber%20yogurt%20red wine vinegar%20pita bread%20tomato%20onion%20lettuce",
        instructions: "To prepare this chicken souvlaki recipe, start by preparing the marinade. Cut the chicken breasts into 2-3 cm pieces and place them in a large bowl, along with all the marinade ingredients. Use your hands to mix really well, cover with plastic wrap and put in the fridge for 30-60 minutes.%20Pour in a blender the olive oil and grated garlic and blend until combined. Remove the skin and the seeds of the cucumber and grate it into a large bowl. Season with salt and pepper and leave aside for 10 minutes.%20 In a bowl, add the cucumber, the blended garlic and oil, the yogurt, 1-2 tbsps of red wine vinegar, a pinch of salt and blend, until the ingredients are combined.%20Preheat a grill or griddle pan on a high heat. Cook the chicken souvlaki (skewers) for about 8 to 10 minutes, turning occasionally, until nicely coloured on all sides and cooked through.%20To serve the chicken souvlaki (skewers), slice 2 red onions and place on a platter; top with the chicken souvlaki (skewers), drizzle with some extra virgin olive oil and a good squeeze of lemon juice."
    },
    {
        id: "89dee273-89cc-45db-be9f-54e43bdaa81d",
        recipe_name: "Surf and Turf",
        cuisine: "American",
        servings: "2",
        total_cook_time: "45",
        image_url: "http://localhost:8080/images/surf-turf.jpeg",
        ingredients_line: "3 tbsp olive oil%201 tbsp butter%201 tbsp onion (Minced)%201bsp white wine%201 tsp worcestershire sauce%201 tsp lemon juice%201 tsp parsley%201 tsp seafood seasoning%201 clove garlic (Minced)%201/8 tsp black pepper%2012 medium shrimp%202 (4oz) steaks%201 tsp steak seasoning",
        ingredients_base: "oil%20butter%20onion%20wine%20worcestershire sauce%20lemon juice%20parsley%20seafood seasoning%20garlic%20black pepper%20shrimp%20steak%20steak seasoning",
        instructions: "Whisk 1 tablespoon olive oil, butter, onion, wine, Worcestershire sauce, lemon juice, parsley, seafood seasoning, garlic, and pepper together in a bowl; add shrimp. Toss to coat evenly. Cover the bowl with plastic wrap and refrigerate for flavors to blend, at least 15 minutes.%20Preheat an outdoor grill for medium-high heat and lightly oil the grate.%20Coat steaks with 2 teaspoons olive oil; sprinkle with steak seasoning.%20Cook steaks on the preheated grill until they are beginning to firm and are hot and slightly pink in the center for medium doneness, 5 to 7 minutes per side.%20Remove shrimp from marinade and grill until they are bright pink on the outside and the meat is opaque, 2 to 3 minutes per side.%20Serve together and enjoy"
    },
    {
        id: "92f267e9-af84-4b12-aea0-b86b77da3543",
        recipe_name: "Lobster Tail",
        cuisine: "American",
        servings: "4",
        total_cook_time: "20",
        image_url: "http://localhost:8080/images/lobster-tail.jpeg",
        ingredients_line: "4 lobster tails%204 tbsp unsalted butter%203 clove garlic%201 tsp paprika%201/2 tsp salt%201/2 tsp black pepper%201 tbsp lemon juice%201 tbsp parsley%20lemon wedges",
        ingredients_base: "lobster%20butter%20garlic%20paprika%20salt%20black pepper%20lemon juice%20parsley%20lemon",
        instructions: "Thaw lobster tails if frozen.%20Preheat broiler.%20Set the oven rack 4 to 6 inches from heat.%20Line a baking sheet with parchment paper or foil. Place lobster tails on the baking sheet.%20Using kitchen shears cut straight along the middle of the top of the lobster shell towards the fins of the tail; do not cut through the fin.%20In a mixing bowl, combine melted butter, garlic, paprika, salt, pepper, lemon juice, and parsley; whisk to combine.%20Brush the tops of the tails with the butter mixture.%20Serve with lemon wedges and more butter sauce"
    },
    {
        id: "4ded492c-f3a6-4465-aeb0-07dfba383279",
        recipe_name: "Cacio e Pepe",
        cuisine: "Roman",
        servings: "2-3",
        total_cook_time: "25",
        image_url: "http://localhost:8080/images/cacio-pepe.jpeg",
        ingredients_line: "4 tbsp olive oil%201 tsp black pepper%20salt%201/2 lb spaghetti%202 tbsp butter%202oz pecorino romano cheese",
        ingredients_base: "oil%20black pepper%20salt%20spaghetti%20butter%20pecorino romano",
        instructions: "Heat 3 tablespoons olive oil and about a teaspoon of black pepper in a medium skillet over medium-low heat until ingredients are fragrant and pepper is barely starting to sizzle, about 1 minute. Set aside.%20Place spaghetti in a large skillet and cover with water. Season with a small pinch of salt, then bring to a boil over high heat, prodding spaghetti occasionally with a fork or wooden spoon to prevent it from clumping. Cook until spaghetti is al dente.%20Using tongs, lift spaghetti and transfer it to the oil/butter mixture.%20Add cheese and remaining tablespoon olive oil to the skillet and stir with a fork until cheese is completely melted.%20Serve immediately"
    },
    {
        id: "552201bc-3bf4-4d9f-a85f-1051d74ff44c",
        recipe_name: "Vegetarian Butter Tofu",
        cuisine: "Indian",
        servings: "2",
        total_cook_time: "35",
        image_url: "http://localhost:8080/images/butter-tofu.jpeg",
        ingredients_line: "1/4 vegetable oil%202 medium onions (Minced)%20salt%203 tbsp ginger (Grated)%205 garlic cloves (Grated)%201 1/2 tsp garam masala%201 tsp turmeric%201 tsp coriander%201/4 tsp fenugreek seeds%204 cardamom pod seeds%2015oz crushed tomatoes%209oz tofu%202 tbsp brown sugar%202 tbsp almond butter%201/4 cup heavy cream",
        ingredients_base: "oil%20onion%20salt%20ginger%20garlic%20garam masala%20turmeric%20coriander%20fenugreek seed%20cardamom seed%20tomato%20tofu%20sugar%20almond butter%20heavy cream",
        instructions: "In a large frying pan, heat the oil or ghee over medium high heat. Add the onions and 1 teaspoon of sea salt and cook, stirring occasionally, until the onions are medium brown, about 8 to 10 minutes. Add the ginger and garlic and cook for 1 minute. Add all of the spices and cook for about 30 seconds, stirring constantly.%20Stir in the crushed tomatoes, scraping the bottom of the pan to remove any browned bits. Add 1/2 cup of water to the pan, reduce the heat to low and simmer slowly for about 15 minutes, or until the sauce thickens and begins to splatter.%20Remove from the heat and allow the sauce to cool for a couple minutes. Transfer the sauce to a blender and blend for 1 minute, or until very smooth.%20Return the sauce to the pan and stir in the tofu over low heat until it is warm. Remove from the heat and stir through the brown sugar, almond butter and cream. Season with salt to taste.%20Serve with rice or naan as desired"
    },
    {
        id: "6dfb3ca2-14b0-4784-82d6-44ddbbdc13fa",
        recipe_name: "Gamjatang",
        cuisine: "Korean",
        servings: "6",
        total_cook_time: "450",
        image_url: "http://localhost:8080/images/pork-bone-soup.jpeg",
        ingredients_line: "3 lb pork neck bones%202 tbsp doenjang%203 green onions%205 cloves garlic%208 cups water%202 tbsp gochujang%201 tbsp gochugaru%202 tbsp soy sauce%201 tbsp fish sauce%202 tbsp mirin%201 tsp coarse black pepper%203 potatoes%201 lb napa cabbage",
        ingredients_base: "pork bone%20doenjang%20green onion%20garlic%20gochujang%20gochugaru%20soy sauce%20fish sauce%20mirin%20black pepper%20potato%20cabbage",
        instructions: "You should have 6 or so lbs of pork neck bones in total. Some will be meatier than others. Keep those for the soup. You will need to blanch and rinse all the pork so you might as well do it all up front.%20Bring to a boil over high heat. Boil for 5 minutes. You will see a mess of scum form. Don't worry. Down the drain it goes.%20Place 3 lbs of the pork neck bones (pick the ones with less meat) into a pot and add the water along with the green onion and 2 whole cloves of garlic.%20Bring to a boil, reduce heat, cover loosely and simmer for 4-5 hours. Longer is better if you have the time.%20Mix 2 Tbsp doenjang with a bit of stock to dilute. Add the reserved pork neck bones and pork hock along thinned doenjang to the pot.%20Simmer 90 minutes.%20After 90 minutes, thin the spice mix with a bit of stock and add it to the soup%20Add the potatoes and cabbage, being careful to submerge the potatoes.%20Serve while hot, Enjoy!"
    },
    {
        id: "015506b3-8615-4072-b497-0c4b3a9e670f",
        recipe_name: "Pad Thai",
        cuisine: "Thai",
        servings: "4",
        total_cook_time: "25",
        image_url: "http//localhost:8080/images/pad-thai.jpeg",
        ingredients_line: "8 oz rice noodles%202 tbsp lime juice%202 tbsp brown sugar%201 tbsp fish sauce%201 tbsp soy sauce%201/4 tsp cayenne pepper%202 tbsp vegetable oil%201 bell pepper (Sliced)%202 cloves garlic (Minced)%202 eggs (Whisked)%201 lb shrimp%20black pepper%202 green onions (Sliced)%201/4 cup roasted peanuts",
        ingredients_base: "rice noodle%20lime juice%20sugar%20fish sauce%20soy sauce%20cayenne pepper%20oil%20bell pepper%20garlic%20egg%20shrimp%20black pepper%20green onion%20peanut",
        instructions: "In a large pot of salted boiling water, cook noodles until al dente. Drain.%20In a small bowl, whisk together lime juice, brown sugar, fish sauce, soy sauce, and cayenne pepper. Set aside.%20In a large nonstick pan over medium-high heat, heat oil. Add bell pepper and cook until tender, about 4 minutes. Stir in garlic and cook until fragrant, about 1 minute more. Add the shrimp and season with salt and pepper. Cook until pink, about 2 minutes per side.%20Push the shrimp and vegetables to one side of the pan and pour in the egg. Scramble until just set then mix with the shrimp mixture. Add the cooked noodles and toss until combined. Pour in the lime juice mixture and toss until the noodles are coated.%20Garnish with green onions and roasted peanuts before serving."
    },
    {
        id: "3beaf39e-3cc9-4f1d-ad54-d636609e61a3",
        recipe_name: "Crispy Fish Burger",
        cuisine: "American",
        servings: "2",
        total_cook_time: "26",
        image_url: "http://localhost:8080/images/fish-burger.jpeg",
        ingredients_line: "1/4 cup all purpose flour%201/2 cup panko%201 tsp salt%203/4 tsp black pepper%201/2 tsp onion powder%201/2 tsp paprika%201/2 tsp thyme%201/4 tsp cayenne pepper%201/4 tsp garlic powder%201 large egg%208oz cod fillet%20vegetable oil%202 burger buns%20tartar sauce%202 cups cabbage%201 carrot%201 green onion%202 tbsp olive oil%201 tbsp apple cider vinegar%201/2 tsp sugar",
        ingredients_base: "flour%20panko%20salt%20black pepper%20onion powder%20paprika%20thyme%20cayenne pepper%20garlic powder%20egg%20cod%20vegetable oil%20burger bun%20tartar sauce%20cabbage%20carrot%20green onion%20olive oil%20apple cider vinegar%20sugar",
        instructions: "Get your dredging station ready: Sift flour onto a plate and spread out. To another plate, add panko, ¼ teaspoon of salt, black pepper, onion powder, paprika, thyme, cayenne pepper, and garlic powder, whisking to combine. In a bowl, whisk egg. Set aside.%20Cut cod into two equal pieces and pat dry with a paper towel. Sprinkle with remaining ¼ teaspoon of salt.%20Dredge each piece of cod in flour, coating all around, shaking off excess.%20Then, dip cod into whisked egg, shaking off excess%20Finally, dredge cod in panko bread crumbs, coating all around, pressing to adhere. You can place on a plate while you are getting your oil ready.%20Place the canola or vegetable oil into a large heavy-duty pot with high/tall sides suitable for frying (I used a high sided cast-iron pot).%20Heat the pot of oil over medium heat. You want an oil temperature of about 360 degrees Fahrenheit.%20Gently lower each piece of cod into the oil, away from you, and cook for 3 minutes. Carefully turn the cod pieces and continue to cook for another 3 minutes or until cod is cooked through, is opaque, and flakes easily with a fork.%20When cooked, carefully remove cod from the oil, sprinkle cod with salt as desired.%20To make coleslaw, mix sliced cabbage, onion, carrot, olive oil, apple cider vinegar and sugar together, combining the ingredients.%20Assemble fish burgers: toast buns (if you like), spread the cut side of each bun with tartar sauce, place piece of fish on bottom buns, top with coleslaw (and any of the other garnish options (if you like), and place top buns over top (with tartar sauce on the inside) to form your fish burgers. Serve and enjoy!",
    },
    {
        id: "b5dd141a-a9d7-4ea6-92b2-5449aef807ab",
        recipe_name: "Smoked Brisket",
        cuisine: "American",
        servings: "8",
        total_cook_time: "600",
        image_url: "http://localhost:8080/images/brisket.jpeg",
        ingredients_line: "12-15 lbs beef brisket%201/4 cup olive oil%201 cup beef rub",
        ingredients_base: "beef%20oil%20beef rub",
        instructions: "The day before cooking, trim the excess fat off the brisket, apply olive oil to brisket. In a separate bowl, combine your dry rub ingredients, and liberally apply to the brisket. Leave in fridge overnight prior to cooking covered in plastic wrap.%20The day of cooking, preheat your smoker to 250 degrees F, we use fruit wood like apple or cherry.%20Place brisket on the smoker (using large tongs) when the temperature is a consistent 250 degrees and insert your two-zone meat probes. One for the meat inserted into the flat, and one to monitor the ambient temperature of the cooking chamber. Smoke for up to six hours until it's ready to wrap.%20When the internal temperature of the brisket is 165 degrees you will carefully remove the brisket and place onto two pieces of pink butcher paper to wrap. Remove the meat probe, tightly wrap the brisket, and then add the meat probe back into the same general area. Place back into the smoker to continue smoking until it's done.%20Continue cooking at 250 degrees for another several hours until the brisket approaches 195 degrees. At that point, you will use your instant read thermometer to insert and probe the flat and the point for that smooth buttery texture as you check for doneness. Anywhere from 195 to 205 it may be done.%20Once the brisket is done, remove, still wrapped in butcher paper, and let it rest for 30 minutes. Slice and serve."

    },
    {
        id: "1d496065-8743-406d-b1ae-7b7fe4be4c50",
        recipe_name: "Peanut Butter Cookies",
        cuisine: "American",
        servings: "32",
        total_cook_time: "120",
        image_url: "http://localhost:8080/images/pb-cookie.jpeg",
        ingredients_line: "1 1/3 cup all purpose flour%201/2 tsp baking soda%201/4 tsp salt%201/2 cup unsalted butter%201/2 cup brown sugar%201/4 cup granulated sugar%201 large egg%203/4 cup peanut butter%201 tsp vanilla extract",
        ingredients_base: "flour%20baking soda%20salt%20butter%20brown sugar%20sugar%20egg%20peanut butter%20vanilla extract",
        instructions: "Whisk the flour, baking soda, and salt together in a medium bowl. Set aside.%20Using a hand mixer or a stand mixer fitted with paddle attachment, beat the butter for 1 minute on high speed until creamy. Switch to medium-high speed and beat in the brown sugar and 1/4 cup (50g) granulated sugar until completely creamed and smooth, about 2 minutes. Add the egg and beat until combined, about 1 minute. Scrape down the sides and bottom of the bowl as needed. Add the peanut butter and vanilla extract and beat until combined.%20Add the dry ingredients to the wet ingredients and beat on low speed until combined. The dough will be very creamy and soft. Cover and chill the cookie dough in the refrigerator for at least 1-2 hours, and up to 3 days.%20Preheat oven to 350°F (177°C). Line large baking sheets with parchment paper or silicone baking mats.%20Place remaining 1/2 cup (100g) of sugar into a bowl. Roll chilled cookie dough into balls, about 1 scant Tablespoon (5/8 ounce or 18g) of dough each. Roll each ball in the sugar and arrange on baking sheets about 2 inches apart. Use a fork to make a criss-cross indent on top of each. To prevent the cookies from over-spreading, after indenting the cookies, use your fingers to reshape into a thicker disc.%20Bake for 11-12 minutes or until the edges appear set and are very lightly browned. The centers will still look very soft.%20Allow cookies to cool on the baking sheet for 5 minutes. After 5 minutes, transfer to a wire rack to cool completely."
    },
    {
        id: "5a4da25e-47e0-41e1-a5d5-f45504e0c340",
        recipe_name: "Chicken Noodle Soup",
        cuisine: "American",
        servings: "8",
        total_cook_time: "40",
        image_url: "http://localhost:8080/images/chicken-noodle.jpeg",
        ingredients_line: "1/2 tbsp butter%202 ribs celery (Diced)%203-4 large carrots (Diced)%201 clove garlic (Minced)%2010 cups chicken stock%201 tsp salt%201/2 tsp black pepper%201/8 tsp rosemary%201/8 tsp sage%201/8 red pepper flakes%205 cups pasta of your choice%203 cups chicken%201 tsp chicken bouillon",
        ingredients_base: "butter%20celery%20carrot%20garlic%20chicken stock%20salt%20black pepper%20rosemary%20sage%20red pepper flakes%20pasta%20chicken%20chicken bouillon",
        instructions: "Add butter, diced celery and carrots to a large stock pot over medium-high heat. Saute for 3 minutes. Add garlic and cook for another 30 seconds.%20Add chicken stock and season the broth with rosemary, sage, crushed red pepper, and salt (definitely TASTE the broth before adding more salt), and pepper. Taste and add a spoonful of “better than bullion” chicken or chicken bouillon cubes or granules as needed.%20Bring broth to a boil. Add noodles (either uncooked homemade egg noodles, or dry store-bought pasta) and cook just until noodles are al dente.%20If using store-bought noodles, be cautious not to overcook them! Remove pot from heat as soon as they are just barely tender. The noodles will continue to cook once you remove the pot from the heat, and you don’t want them mushy.%20Add chicken meat. Taste the broth again and add more seasonings, if needed.%20Store leftovers in an airtight container in the refrigerator for 4-5 days, depending on the freshness of the chicken you used."
    },
    {
        id: "3e4672c6-a10c-4001-b119-48bd9b9d5065",
        recipe_name: "Banana Bread with Pecans",
        cuisine: "American",
        servings: "1",
        total_cook_time: "60",
        image_url: "http://localhost:8080/images/banana-bread.jpeg",
        ingredients_line: "1 1/2 cups all purpose flour%201 tsp baking soda%201/2 cup unsalted butter%201/3 cup granulated sugar%201/4 cup brown sugar%201/2 tsp salt%202 large eggs%203 ripe bananas%201 tsp vanilla extract%201 cup pecans",
        ingredients_base: "flour%20baking soda%20butter%20sugar%20brown sugar%20salt%20egg%20banana%20vanilla extract%20pecan",
        instructions: "Preheat the oven to a 350°F. Grease a 9x5-inch loaf pan or line with parchment paper, leaving an overhang on the sides to lift the baked bread out.%20Mash 3 very ripe bananas with a fork or potato masher until chunky applesauce consistency.%20In a medium bowl, combine and whisk 1 1/2 cups all-purpose flour and 1 tsp baking soda. Set aside.%20In a large mixing bowl, cream together 8 tbsp softened unsalted butter, 1/3 cup granulated sugar, 1/4 cup brown sugar and 1/2 tsp fine salt until smooth (about 2 mins on high speed).%20Add mashed bananas, 2 large eggs and 1 tsp vanilla extract to the batter. Beat on low just until combined, about 30 seconds.%20Combine dry and wet ingredients and beat on low or stir in with a spatula just until combined.%20Gently fold in coarsely chopped pecans.%20Spread the batter evenly into the prepared loaf pan. Sprinkle more coarsely chopped pecans over the top of the bread and bake at 350°F for 50-60 minutes, or until a toothpick inserted into the center of the bread comes out clean. (My oven takes 55 minutes). Let banana bread rest 5 minutes before transferring to a wire rack to cool."
    }
]